apiVersion: apps/v1
kind: Deployment
metadata:
  name: boid-sim
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boid-sim
  template:
    metadata:
      labels:
        app: boid-sim
    spec:
      containers:
      - name: boid-web
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80