apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: boid-sim
spec:
  rules:
  - host: "{{ .Values.ingress.host }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: boid-sim
            port:
              number: 80