image:
  repository: yourusername/boid-sim
  tag: arm64-latest
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: boid.example.com
      paths:
        - path: /
          pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi